WestCoast-Cars-prototype/Models/VehicleModel.cs
using WestCoast_Cars.ViewModels;

namespace WestCoast_Cars.Models;

public class VehicleModel
{
  /* METHODS */
  public List<VehicleViewModel> GetVehicles()
  {
    // Hämta datat någonstans ifrån...
    // Fejk anrop till en databas...
    List<VehicleViewModel> list = [
      new VehicleViewModel{Id=1, RegNo="ABC123", Make="Volvo", Model="V60",ModelYear=2019},
      new VehicleViewModel{Id=1, RegNo="DEF456", Make="Ford", Model="Mustang MACH-E",ModelYear=2023},
      new VehicleViewModel{Id=1, RegNo="GHI789", Make="KIA", Model="EV6",ModelYear=2022},
    ];

    return list;
  }

  public VehicleViewModel Find(int id)
  {
    return new VehicleViewModel { Id = 1, RegNo = "DEF456", Make = "Ford", Model = "Mustang MACH-E", ModelYear = 2023 };
  }
}

WestCoast-Cars-prototype/ViewModels/VehicleViewModel.cs
namespace WestCoast_Cars.ViewModels;

public class VehicleViewModel
{
  public int Id { get; set; }
  public string RegNo { get; set; } = "";
  public string Make { get; set; } = "";
  public string Model { get; set; } = "";
  public int ModelYear { get; set; }
}

WestCoast-Cars-prototype/Controllers/VehiclesController.cs
using Microsoft.AspNetCore.Mvc;
using WestCoast_Cars.Models;
using WestCoast_Cars.ViewModels;

namespace WestCoast_Cars.Controllers
{
    [Route("vehicles")]
    public class VehiclesController : Controller
    {
        // GET: VehiclesController
        public IActionResult Index()
        {
            VehicleModel model = new VehicleModel();
            List<VehicleViewModel> vehicleList = model.GetVehicles();
            return View("Index", vehicleList);
        }

        // https://domainnamn/vehicles/5 GET
        [HttpGet("details/{id}")]
        public IActionResult Details(int id)
        {
            VehicleModel model = new();
            VehicleViewModel vehicle = model.Find(id);
            return View("Details", vehicle);
        }

        // Parvisa action metoder för att först hämta ett inmatningsformulär
        // och en för att skicka in nytt data(ny bil)...
        [HttpGet("create")]
        public IActionResult Create()
        {
            // Skapa ett nytt objekt av typen VehicleViewModel och skicka den till vy (Create)...
            VehicleViewModel vehicle = new();
            return View("Create", vehicle);
        }

        [HttpPost("create")]
        public IActionResult Create(VehicleViewModel vehicle)
        {
            // Spara ner en ny bil någonstans...
            return RedirectToAction(nameof(Index));
        }
    }
}

WestCoast-Cars-prototype/Views/Vehicles/Create.cshtml
@model WestCoast_Cars.ViewModels.VehicleViewModel

<section>
  <h1>Lägg till ny bil</h1>
  <form asp-action="Create">
    <div>
      <label for="RegNo">Registreringsnummer</label>
      <input asp-for="RegNo" type="text">
    </div>
    <div>
      <label for="Make">Tillverkare</label>
      <input asp-for="Make" type="text">
    </div>
    <div>
      <label for="Model">Modell</label>
      <input asp-for="Model" type="text">
    </div>
    <div>
      <label for="ModelYear">Årsmodell</label>
      <input asp-for="ModelYear" type="text">
    </div>
    <div>
      <button>Spara</button>
    </div>
  </form>
</section>

WestCoast-Cars-prototype/Views/Vehicles/Details.cshtml
@model WestCoast_Cars.ViewModels.VehicleViewModel
<section>
  
  @* Vill jag skapa en lista av detaljer om bilen som är vald i listan... *@
  <h1>Information om vald bil</h1>
  <h2>@Model.Make - @Model.Model - @Model.ModelYear</h2>
  <p>Registreringsnummer @Model.RegNo</p>
  <a asp-action="index">Gå till listan av bilar</a>
</section>

WestCoast-Cars-prototype/Views/Vehicles/Index.cshtml
@model IList<WestCoast_Cars.ViewModels.VehicleViewModel>

<h1>Aktuella bilar till försäljning</h1>
<section>
  <h4><a asp-action="Create" asp-controller="Vehicles">Lägg till ny bil</a></h4>
  @* Loopa/Iterera igenom alla bilar som jag får via controller metoden... *@
  @foreach (var vehicle in Model) {
    @* TagHelper för att skapa en länk(<a>) *@
    @* https://localhost:5001/vehicles/details/1 *@
    <div>
      <a asp-action="details" asp-controller="vehicles" asp-route-id="@vehicle.Id">@vehicle.Make | @vehicle.Model | @vehicle.ModelYear</a>
    </div>
  }
</section>